### ISSUE TITLE
probably patched in 10.0.25398.2258

### ISSUE THREAD

**Issue by zecoxao** [Kudayasu/Artifice#2]
![image](https://github.com/Kudayasu/Artifice/assets/1857828/42447d2e-5009-4bb8-bd3b-f80235cf238b)
![image2](https://github.com/Kudayasu/Artifice/assets/1857828/56f6b86f-c584-4f23-9437-0c7a04199f46)
![image3](https://github.com/Kudayasu/Artifice/assets/1857828/5feb2ce7-3400-46d8-9439-3357aacff9ec)

**Comment by Kudayasu** [comment]
Should be fixed now, thanks for letting me know.

**Comment by Kudayasu** [comment]
Should be fixed now, thanks for letting me know.

**Comment by 06066060606060** [comment]
Thanks a lot Kudayasu version 1.2 fixed all the problems I had!
successfully tested on Series X october update (10.0.25398.2453)
