### ISSUE TITLE
Exception encountered: 0x80070057 : Failed to launch the application.

### ISSUE THREAD

**Issue by toastmod** [Kudayasu/Artifice#4]
Not sure what is causing this to happen. Installing the universal package works fine. Should this work on 
retail dev mode?

I also tried rebooting (deleting sideloaded games/apps) in and out of dev mode.

![image](https://github.com/Kudayasu/Artifice/assets/10666062/71e3b48b-0f01-481a-a2a1-f6d6494f1055)

**Comment by toastmod** [comment]
0x80070057 looks to be a storage related exception? I have a 5gb dev space though. I wouldn't think I'd need more right?

**Comment by Kudayasu** [comment]
`0x80070057 The parameter is incorrect` - initial guess is that this is another PATH issue. 

For yours in particular, the exact source is most likely [this line](https://github.com/Kudayasu/Artifice/blob/main/Artifice/MainWindow.xaml.cs#L876)

With that in mind, some things you can try:

- Extracting the publish folder from the zip directly to your **Desktop** and running it from there.
- Extracting the publish folder to similar locations mentioned in the [previous issue](https://github.com/Kudayasu/Artifice/issues/3#issuecomment-1769789228)
- Ensure `XboxWDPDriver.exe`  is being ran (Task Manager)
- Ensure you're able to invoke the exe directly outside of Artifice, i.e. `\publish\Scratch\WDP\XboxWDPDriver.exe` **XboxWdpDriver.exe /X:XBOXONE**

**Comment by toastmod** [comment]
Totally missed that there was a pre-built zip in released. My bad.
Everything is working, thanks!
