### ISSUE TITLE
App is stuck on first step, nothing happens.

### ISSUE THREAD

**Issue by SegaGameBoyStation** [Kudayasu/Artifice#5]
I have my xbox Series X in DevMode, Artiface on my desktop. I tried turning off login requirements to connect to the Xbox, using https://IP.address:PortNumber, https://IP.address, IP.address and IP.Address:PortNumber. No matter what, Artiface never goes beyond the "Initialised: message.
What am I doing wrong here?

**Comment by Kudayasu** [comment]
If you attempt the process immediately after starting Artifice (i.e. the program hangs), give it a few seconds to initialize first, then try using the hostname instead. Using the IP is perfectly valid mind you, but it's worth exploring your options.
