### ISSUE TITLE
Stuck at Step 9 - Invoking AKC

### ISSUE THREAD

**Issue by FreeTheTech101** [Kudayasu/Artifice#6]
### Software Info:

App Version: v1.2
Xbox OS Version: 10.0.22000.3038 (November 2021)
Xbox Console: Xbox One X (XDK Test Kit)

### Issue:

During step 9, Artifice will hang on "Invoking AKC":

![image](https://github.com/Kudayasu/Artifice/assets/7614507/071e8169-f4f7-40dc-bf53-f2f90290401b)

While following the execution, the private-key based SSH attempt throws an SshConnectionException, which skips straight to attempting a disconnect and a dispose which fails. The exception message itself is "An established connection was aborted by the server."

The console itself is currently permanently activated via [these instructions](https://torushyperv.github.io/xb1-xdk-activation-trick/xb1-xdk-activation-trick.html), which I am unsure if they interfere in any way.

**Comment by tuxuser** [comment]
Artifice is not compatible with non-UWP devkits.

You can use "xbrun" to spawn telnetd.exe as SYSTEM.

**Comment by Kudayasu** [comment]
In this instance, it's not a kit-type compatibility issue, rather it's an SSH version issue. Unfortunately, I don't have an exact minimum system version for Xbox regarding when they actually did merge in the ['NT AUTHORITY\SYSTEM' pull](https://github.com/PowerShell/openssh-portable/pull/479), as OpenSSH on Xbox always lagged behind by quite a large amount. My best guess for minimum system version compatibility would be [22621](https://support.xbox.com/en-US/help/hardware-network/settings-updates/system-updates-2022).

Tux's mention is correct though, ideally you'd be using the [XDK](https://xboxoneresearch.github.io/wiki/development/xtf-apis/) tooling if you're working with any sort of non-retail devkit.

**Comment by FreeTheTech101** [comment]
The above does sum it up, after using `xbrun /X <IP> "telnetd.exe cmd.exe 23"` to spawn a telnet, checking the OpenSSH version via `%SystemRoot%\System32\OpenSSH\sshd.exe -V` returns the following:

```
OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2
usage: sshd [-46DdeiqTt] [-C connection_spec] [-c host_cert_file]
            [-E log_file] [-f config_file] [-g login_grace_time]
            [-h host_key_file] [-o option] [-p port] [-u len]
```

From that, we can see it's running [this build](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.1.0.0p1-Beta) of Win32-OpenSSH.

Regardless, thank you for pointing me in the correct direction!
